### ISSUE TITLE
programatically open/close store

### ISSUE THREAD

**Issue by divramod** [ngrx/store-devtools#11]
hey, 

thx for your awesome work on the devtools.

i am using ngrx/devtools with ionic 2 and cordova.

so i wanted to ask how i can programatically 
- toggle visibility
- change the position
- change the size

thx in advance

**Comment by MikeRyan52** [comment]
Number of APIs have been improved to get this working. If you still need help with this, feel free to open a new issue in ngrx/store-log-monitor 

Thanks!
