### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by MarkPieszak** [ngrx/store-devtools#15]
Looks we should look into updating numerous dependencies (see if it breaks any core logic).

Angular2 is @ beta 16.
RxJs @ beta 6.
es6shim, lodash, typings, and zone all have many updates as well.

https://david-dm.org/ngrx/devtools#info=devDependencies&view=table

https://david-dm.org/ngrx/devtools#info=peerDependencies&view=table

**Comment by MikeRyan52** [comment]
Fixed in v2
