### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by Hongbo-Miao** [ngrx/store-devtools#19]
Thanks for this great tool!

Just a suggestion. Maybe in the future, create a dev tool as Chrome extension.
Like this [ExtensionRedux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en-US).

**Comment by Hongbo-Miao** [comment]
Right now it just cover my other part of my app. And I want it to be float and can be moved.

**Comment by Hongbo-Miao** [comment]
This can take advantage of undocking the console into separate window.

**Comment by nosachamos** [comment]
This would be seriously awesome.

**Comment by Hongbo-Miao** [comment]
It is not mentioned in ReadMe file. But I can use Chrome extension Redux DevTools successfully now.

**Comment by r-park** [comment]
@Hongbo-Miao what did you do to get Chrome devtools extension working?

**Comment by Hongbo-Miao** [comment]
@r-park 
I installed both
@ngrx/store-devtools (v2)
@ngrx/store-log-monitor (This seems not really need, I am using it sometimes for in-page dev tool sometimes) following the ReadMe file.
Then just open [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en-US), no more steps needed.

**Comment by Hongbo-Miao** [comment]
Okay, I will close this issue, because 
https://github.com/ngrx/store-log-monitor/blob/master/README.md
add the explanation now:

> Port of redux-devtools-log-monitor for Angular 2 and @ngrx/store-devtools

So I think it is officially supported now.
