### ISSUE TITLE
Universal apps can't render with devtools

### ISSUE THREAD

**Issue by dballance** [ngrx/store-devtools#22]
Filed an issue for tracking even though we discussed in gitter.

Currently the below section prevents universal rendering of the application due to the call to window.

```
const REDUX_DEVTOOLS_EXTENSION_PROVIDER = {
  provide: REDUX_DEVTOOLS_EXTENSION,
  useFactory() {
    if (window && (window as any).devToolsExtension) {
      return (window as any).devToolsExtension;
    }
    return null;
  }
};
```

Can be rectified by modifying the check for the window object.

```
const REDUX_DEVTOOLS_EXTENSION_PROVIDER = {
  provide: REDUX_DEVTOOLS_EXTENSION,
  useFactory() {
    if (typeof window !== 'undefined' && (window as any).devToolsExtension) {
      return (window as any).devToolsExtension;
    }
    return null;
  }
};
```

Will try to send a PR tonight.

**Comment by dballance** [comment]
#23 should rectify, but still have questions about how this will interact with HMR / server state hydration.

**Comment by MikeRyan52** [comment]
Merged
