### ISSUE TITLE
enable sourcemaps?

### ISSUE THREAD

**Issue by rweng** [ngrx/store-devtools#29]
Hi there,

I'd like to discuss if we should enable sourcemaps in the `tsconfig.json`. Reason: When I had an error in one of my reducers. The error was obscured by store-devtools, which (loggs out the error)[https://github.com/ngrx/store-devtools/blob/master/src/reducer.ts#L37], but it seems when sourcemaps are not enabled chrome has problems detecting the sourcemaps of files further up the stack. I found [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=376409) in Chrome.

Anyhow, it could be that my webpack configuration is the problem, but when I checked out the projected in build it w/ sourcemaps enabled it got better errors. What's your take on this? Any reasons not to ship sourcemaps?

Thanks, Robin

**Edit**:  Setting the webpack config to `devtool: 'source-map'` solves the problem, so feel free to close the issue if you consider it irrelevant (I leave it open since I'd like to know your thoughts on why sourcemaps are disabled)

**Comment by MikeRyan52** [comment]
Fixed in v3.0.2
