### ISSUE TITLE
documentation unclear

### ISSUE THREAD

**Issue by select** [ngrx/store-devtools#32]
The readme states

```
@NgModule({
  imports: [
    StoreModule.provideStore(rootReducer),
    // Note that you must instrument after importing StoreModule
    StoreDevtoolsModule.instrumentStore({
      maxAge: 5,
      monitor: monitorReducer
    })
  ]
})
```
however I have no idea where you go the `monitorReducer` from. 

Also I'm using (maybe due to old code) 'providers: []' to get init the store.

**Comment by MikeRyan52** [comment]
`monitorReducer` is a reducer function for containing a monitor component's state. See [@ngrx/store-log-monitor](https://github.com/ngrx/store-log-monitor) for an example monitor.

The preferred way to use the devtools now is using the Chrome extension. I've updated the README with instructions.

**Comment by select** [comment]
perfect, that is much better
