### ISSUE TITLE
Can't export state using redux devtools chrome extension

### ISSUE THREAD

**Issue by JohnKis** [ngrx/store-devtools#40]
Hi there,

I found that when I click on export in the chrome extension, nothing happens. First I thought it's an issue with Chrome or the extension, but it's working fine for non ngrx based redux apps.

## To replicate the issue
- Install the chrome extension
- Visit the ngrx example app (http://ngrx.github.io/example-app/#/)
- Open the extension
- Click export
- Observe that nothing happens

## Expected behaviour
I'd expect clicking the export button to download the exported state. Just like it does doing so on http://zalmoxisus.github.io/examples/counter/

Chrome version: 55.0.2883.75 (64-bit) (Mac)
Redux DevTools extension version: 2.11.0.4
Node version: v6.3.0
nom version: 3.10.3

**Comment by zalmoxisus** [comment]
Fixed in `2.11.1` version of the extension. Please update it from Chrome Store.

**Comment by JohnKis** [comment]
Wow, that was ultra-fast :) Thank you very much!
