### ISSUE TITLE
Skip/Dispatch not working after chrome extension upgrade to version 2.12.1

### ISSUE THREAD

**Issue by bahaha** [ngrx/store-devtools#46]
hi,

I have used this awesome devtools for chrome,
and it works well until the extension upgrading to 2.12.1.

I have tried to use the devtools with demos from [redux-devtools](https://github.com/zalmoxisus/redux-devtools-extension#demo), it works fine.
But with the [example-app](https://github.com/ngrx/example-app), the skip/dispatch didn't work anymore.

the redux-devtools extension for Firefox works well, too.

did someone have experienced the same problem?

**Comment by zalmoxisus** [comment]
Should be fixed in `2.12.2`. Please update it from Chrome Store.

**Comment by bahaha** [comment]
it works after update it from Chrome Store, thanks
