### ISSUE TITLE
Error: Actions may not have an undefined "type" property. When using @ngrx/effects.

### ISSUE THREAD

**Issue by damnko** [ngrx/store-devtools#59]
Hi, I am getting the following error when I dispatch an action that triggers an effect via `@ngrx/effects`
```
Actions may not have an undefined "type" property. Have you misspelled a constant?
```
The issue can be reproduced by cloning [this repo](https://github.com/damnko/angular2-ngrx-store). It happens only when the Chrome extension is installed.

**Browser**: Google Chrome v57.0.2987.133 (64-bit)
**OS**: Linux Mint 17.2 Rafaela (64-bit)
**NPM**: v4.1.2
**NodeJs**: v7.4.0

**Comment by MikeRyanDev** [comment]
This effect is causing you dispatch items that are not actions: https://github.com/damnko/angular2-ngrx-store/blob/master/src/app/effects/index.ts#L10

Update your effect decorator to prevent dispatching if the effect's intention is not to cause new actions to enter the stream:

```
@Effect({ dispatch: false })
```

**Comment by damnko** [comment]
Wow thanks a lot for your help. That was fast and super helpful.
